### PR TITLE
native: make sed substitutions work on OSX

### PR DESCRIPTION
**Pull request by kortschak**
The syntax for "\n" inclusion in subsutition strings for OS X is
incompatible with GNU sed. This logic fails the script when a call to go
generate is made without a functional sed.

The logic here provides a potential hook for OS X-dependent devs to alter
the warning string to something that OS X sed will work with, without
breaking GNU sed substitutions.

### CODE REVIEW

**Comment by kortschak** [comment]
This needs to be tested by someone with OS X. Testing involves running `go generate` and should result in the emission of a warning and non-zero exit status.

**Comment by vladimir-ch** [comment]
I tested it on Yosemite and the output is:
```
single_precision generate script requires GNU sed or equivalent.
native.go:5: running "./single_precision": exit status 1
```

**Comment by kortschak** [comment]
That's what I want. Thanks.

I'll factor the absent tests warning string out and merge. Then somone on OS X can replace the exit and warning message with something that works there without breaking GNU sed.

**Comment by kortschak** [comment]
PTAL @vladimir-ch 

I suspect that if you replace the WARNING string with in the condition (replacing the message and exit) `//$\n// Float32 implementations are autogenerated and not directly tested.$\n` or something similar it will work on OS X. Would you please try that.

**Comment by vladimir-ch** [comment]
The following modification works. Output of `git diff` after running `go generate`:

```diff
diff --git a/native/single_precision b/native/single_precision
index bafc91c..2c9ddee 100755
--- a/native/single_precision
+++ b/native/single_precision
@@ -9,8 +9,9 @@ WARNING="//\n// Float32 implementations are autogenerated and not directly teste
 # Reject sed that cannot include "\n" in the substitution.
 if echo -e 'foo' | sed 's_foo_\n_' | grep 'n' >/dev/null
 then
-       echo "single_precision generate script requires GNU sed or equivalent."
-       exit 1
+    WARNING='//\
+// Float32 implementations are autogenerated and not directly tested.\
+'
 fi
 
 # Level1 routines.
```

**Comment by kortschak** [comment]
That works with GNU as well. great!

PTAL

I'll change issue title and squash if it's all OK.

**Comment by vladimir-ch** [comment]
Shouldn't be there a punctuation mark in "Generated code do not edit"?

LGTM

**Comment by kortschak** [comment]
There should. Leaving for later.

**Comment by kortschak** [comment]
Jumped the gun with deleting the branch and confused travis. Cannot be unconfused AFAICS.

Integration tests passed.

**Pull request merged**
