### PR TITLE
use go generate to generate benchmark code

### PR DESCRIPTION
**Pull request by fhs**

### CODE REVIEW

**Comment by btracey** [comment]
The original isn't great code. I think the better fix is to have the benchmark code itself live in testblas, and then have the BenchmarkXxx stubs live in goblas and cblas.

**Comment by fhs** [comment]
Maintaining this amount of benchmark code by hand will be a lot work. I still think everything should be autogenerated, including the stubs if you end up factoring out some of the code in a package like testblas.

You have less than 300 lines of code that generates lots of benchmarks. You can clean it up a little and maybe make it shorter by using the reflect package to get the method parameter names and types.

**Comment by btracey** [comment]
Sorry, I didn't mean to suggest it shouldn't be automated. I was suggesting the actual benchmark code live in testblas, and then just have stubs in goblas and cblas like is there for the other benchmarks.

**Comment by fhs** [comment]
This doesn't merge anymore. Closing.

**Pull request closed without merging**
