### PR TITLE
cgo: note that BLAS is underspecified

### LINKED ISSUE #118: doc: clearly document that different BLAS implementations have different behaviour
Moving from gonum/matrix#109.

We should also point out that we test against OpenBLAS in the cgo implementation.

### PR DESCRIPTION
**Pull request by kortschak**
@btracey Please take a look.

Fixes #118.

### CODE REVIEW

**Comment by btracey** [comment]
Lgtm.
We probably want a similar disclaimer in native saying that blas didn't specify man and that the behavior of native with nan may change

**Comment by kortschak** [comment]
>We probably want a similar disclaimer in native saying that blas didn't specify man and that the behavior of native with nan may change

How would we change it? and why?

**Comment by btracey** [comment]
Efficiency reasons. I don't have any direct plans, but it seems like ignoring NaNs to various degrees can be notably faster (looking at the openblas thread)

**Comment by kortschak** [comment]
We can probably leave the note for now since we say that the blas implementations follow the BLAS standard.

**Pull request merged**
