### PR TITLE
Aligned benchmark behavior with their name and fixed duplicate benchmark

### PR DESCRIPTION
**Pull request by btracey**

### CODE REVIEW

**Comment by fhs** [comment]
Needs "fixes #82" in the commit message, or close it once you submit.

**Comment by btracey** [comment]
Thanks.

**Comment by btracey** [comment]
Is this good?

**Comment by fhs** [comment]
LGTM

I would write the benchmarks in a more compact way as I described in #82, but leaving it up to you.

**Comment by kortschak** [comment]
I like that terse form, it's very easy to read.

**Comment by btracey** [comment]
I'm submitting now as is, and I'll make a new PR to fix all of the benchmarks at once.

**Pull request merged**
